grpc_port: 9191
state_file: "cache.json"
operator_config: "EIGEN_OPERATOR_CONFIG"
network: "testnet"
eth_oracle:
  rpc:
    local: "http://127.0.0.1:8545"
    testnet: "TESTNET_HOLESKY_ENDPOINT"
    mainnet: "MAINNET_ENDPOINT"
  contract_addrs:
    service_manager: "0xa559CDb9e029fc4078170122eBf7A3e622a764E4"
    price_feeds:
      btc: "0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c"
      eth: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    zenbtc_controller:
      ethereum:
        testnet: "0x912D79F8d489d0d007aBE0E26fD5d2f06BA4A2AA"
  network_name:
    mainnet: "Ethereum Mainnet"
    testnet: "Holešky Ethereum Testnet"
solana_rpc:
  testnet: "https://api.testnet.solana.com"
  mainnet: ""
proxy_rpc:
  url: #To be provided by the Zenrock team
  user: #To be provided by the Zenrock team
  password: #To be provided by the Zenrock team
neutrino:
  path: "/root-data/neutrino"
