grpc_port: 9191
state_file: "cache.json"
operator_config: "EIGEN_OPERATOR_CONFIG"
network: "testnet"
eth_oracle:
  rpc:
    local: "http://127.0.0.1:8545"
    testnet: "TESTNET_HOLESKY_ENDPOINT"
    mainnet: "MAINNET_ENDPOINT"
  contract_addrs:
    service_manager: "0xa559CDb9e029fc4078170122eBf7A3e622a764E4"
    price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    network_name: "Holešky Ethereum Testnet"
solana_rpc:
  testnet: "https://api.testnet.solana.com"
  mainnet: ""
proxy_rpc:
  url: ""
  user: ""
  password: ""
neutrino:
# root path to your setup folder, where validator/sidecar configuration files/data resides
  path: "/<APP-DIR>/neutrino"









