grpc_port: 9191
state_file: "cache.json"
operator_config: "EIGEN_OPERATOR_CONFIG"
network: "testnet"
eth_oracle:
  rpc:
    local: "http://127.0.0.1:8545"
    testnet: "TESTNET_HOLESKY_ENDPOINT"
    mainnet: "MAINNET_ENDPOINT"
  contract_addrs:
    service_manager: "0x3AD648DfE0a6D80745ab2Ec97CB67c56bfBEc032"
    price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    network_name: "Holešky Ethereum Testnet"
solana_rpc:
  testnet: "https://api.testnet.solana.com"
  mainnet: ""
proxy_rpc:
  url: ""
  user: ""
  password: ""
neutrino:
  path: "/root-data/neutrino"









