grpc_port: 9191
state_file: "cache.json"
operator_config: "EIGEN_OPERATOR_CONFIG"
eth_oracle:
  rpc:
    local: "http://127.0.0.1:8545"
    testnet: "TESTNET_HOLESKY_ENDPOINT"
    mainnet: "MAINNET_ENDPOINT"
  network: "testnet"
  contract_addrs:
    service_manager: "0xb48F00b89A4017f78794F35cb1ef540EDA5d201B"
    price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    network_name: "Holešky Ethereum Testnet"
